# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "rspec", "2.12.0"
gem "mocha", "0.13.1"
gem "simplecov", "0.7.1"

# gem "grancher"

gem "yard"
gem "yard-tomdoc"
gem "redcarpet"

# gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.4", :group => [:development, :test]

gem "teamocil", :group => [:development, :test]
# vim: syntax=ruby
